export const initialManagers = [
  { id: "mgr-1", name: "Subham Jamliya", role: "store_manager", phone: "9826012345", email: "vijaynagar@papaveg.com", status: "Active" },
  { id: "mgr-2", name: "Rashid Khan", role: "store_manager", phone: "9988112233", email: "palasia.cloud@papaveg.com", status: "Active" },
  { id: "mgr-3", name: "Aarav Sharma", role: "store_manager", phone: "9111223344", email: "ujjain.express@papaveg.com", status: "Active" },
  { id: "mgr-4", name: "Vikram Singh", role: "store_manager", phone: "9893012345", email: "bhopal.mpnagar@papaveg.com", status: "Active" },
  { id: "mgr-5", name: "Vikram Singh", role: "store_manager", phone: "9827011223", email: "vikram.singh@papaveg.com", status: "Active" },
  { id: "mgr-6", name: "Manoj Verma", role: "store_manager", phone: "9926077889", email: "manoj.verma@papaveg.com", status: "Active" },
  { id: "mgr-7", name: "Sunita Rao", role: "store_manager", phone: "9755033445", email: "sunita.rao@papaveg.com", status: "Active" },
  { id: "mgr-8", name: "Deepak Gupta", role: "store_manager", phone: "9826255667", email: "deepak.gupta@papaveg.com", status: "Active" },
  { id: "mgr-9", name: "Kavita Joshi", role: "store_manager", phone: "9977544332", email: "kavita.joshi@papaveg.com", status: "Active" },
  { id: "mgr-10", name: "Rohan Mehta", role: "store_manager", phone: "9893211223", email: "rohan.mehta@papaveg.com", status: "Active" },
  { id: "mgr-11", name: "Sanjay Trivedi", role: "store_manager", phone: "9754112233", email: "sanjay.trivedi@papaveg.com", status: "Active" },
  { id: "mgr-12", name: "Neha Deshmukh", role: "store_manager", phone: "9926889900", email: "neha.deshmukh@papaveg.com", status: "Active" }
];

export const initialStores = [];

export const initialStoreApprovals = [
  {
    _id: "approval-1",
    storeId: "store-101",
    storeName: "Papa Veg Pizza - Vijay Nagar",
    storeCode: "PVP-IND-01",
    storeType: "Regular",
    submittedBy: "Subham Jamliya",
    managerId: "mgr-1",
    managerName: "Subham Jamliya",
    phone: "9826012345",
    email: "vijaynagar@papaveg.com",
    address: {
      line1: "Shop 12, Orbit Mall, A.B. Road",
      city: "Indore",
      state: "Madhya Pradesh",
      pincode: "452010",
      coordinates: [75.8954, 22.7486]
    },
    documents: [
      { type: "FSSAI License", url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf", name: "fssai_license.pdf" },
      { type: "GST Registration", url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf", name: "gst_certificate.pdf" },
      { type: "NOC Document", url: "https://images.unsplash.com/photo-1557804506-669a67965ba0", name: "fire_noc.jpg" }
    ],
    remarks: "Requesting approval for launching in East Indore region. All documents attached.",
    status: "Pending",
    approvedBy: null,
    approvedAt: null,
    rejectionReason: null,
    createdAt: new Date(Date.now() - 7200000).toISOString()
  },
  {
    _id: "approval-2",
    storeId: "store-102",
    storeName: "Papa Veg Pizza - Palasia Cloud Kitchen",
    storeCode: "PVP-IND-02",
    storeType: "Cloud Kitchen",
    submittedBy: "Rashid Khan",
    managerId: "mgr-2",
    managerName: "Rashid Khan",
    phone: "9988112233",
    email: "palasia.cloud@papaveg.com",
    address: {
      line1: "Basement 2, Shekhar central",
      city: "Indore",
      state: "Madhya Pradesh",
      pincode: "452001",
      coordinates: [75.8763, 22.7196]
    },
    documents: [
      { type: "FSSAI License", url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf", name: "fssai_license.pdf" },
      { type: "Municipal Trade License", url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf", name: "trade_license.pdf" }
    ],
    remarks: "Cloud Kitchen setup targeting Central Indore. Documents verified.",
    status: "Pending",
    approvedBy: null,
    approvedAt: null,
    rejectionReason: null,
    createdAt: new Date(Date.now() - 14400000).toISOString()
  },
  {
    _id: "approval-3",
    storeId: "store-103",
    storeName: "Papa Veg Pizza - Ujjain Tower Chowk",
    storeCode: "PVP-UJN-01",
    storeType: "Express",
    submittedBy: "Aarav Sharma",
    managerId: "mgr-3",
    managerName: "Aarav Sharma",
    phone: "9111223344",
    email: "ujjain.express@papaveg.com",
    address: {
      line1: "Shop 4, Freeganj Tower area",
      city: "Ujjain",
      state: "Madhya Pradesh",
      pincode: "456010",
      coordinates: [75.7892, 23.1764]
    },
    documents: [
      { type: "FSSAI License", url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf", name: "fssai_license.pdf" }
    ],
    remarks: "Express outlet model near Mahakal corridor area.",
    status: "Approved",
    approvedBy: "Super Admin",
    approvedAt: new Date(Date.now() - 86400000).toISOString(),
    rejectionReason: null,
    createdAt: new Date(Date.now() - 172800000).toISOString()
  },
  {
    _id: "approval-4",
    storeId: "store-104",
    storeName: "Papa Veg Pizza - Bhopal MP Nagar",
    storeCode: "PVP-BPL-01",
    storeType: "Regular",
    submittedBy: "Vikram Singh",
    managerId: "mgr-4",
    managerName: "Vikram Singh",
    phone: "9893012345",
    email: "bhopal.mpnagar@papaveg.com",
    address: {
      line1: "Zone I, Maharana Pratap Nagar",
      city: "Bhopal",
      state: "Madhya Pradesh",
      pincode: "462011",
      coordinates: [77.4326, 23.2324]
    },
    documents: [
      { type: "FSSAI License", url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf", name: "fssai_license.pdf" }
    ],
    remarks: "Opening outlet in prime Bhopal location.",
    status: "Rejected",
    approvedBy: "Super Admin",
    approvedAt: new Date(Date.now() - 43200000).toISOString(),
    rejectionReason: "Incomplete Documents",
    createdAt: new Date(Date.now() - 259200000).toISOString()
  }
];

export const initialStorePerformance = [
  {
    _id: "perf-1",
    storeId: "store-1",
    storeName: "Papa Veg Pizza - Indore Central",
    date: "2026-06-20",
    totalOrders: 280,
    completedOrders: 274,
    cancelledOrders: 6,
    revenue: 56000,
    avgOrderValue: 200,
    avgPreparationTime: 12,
    avgDeliveryTime: 22,
    customerRating: 4.8,
    inventoryWaste: 2.2,
    performanceScore: 94,
    status: "Active",
    storeType: "Regular",
    city: "Indore",
    createdAt: new Date().toISOString()
  },
  {
    _id: "perf-2",
    storeId: "store-2",
    storeName: "Papa Veg Pizza - Bhopal Zone",
    date: "2026-06-20",
    totalOrders: 220,
    completedOrders: 215,
    cancelledOrders: 5,
    revenue: 44000,
    avgOrderValue: 200,
    avgPreparationTime: 14,
    avgDeliveryTime: 24,
    customerRating: 4.6,
    inventoryWaste: 2.8,
    performanceScore: 88,
    status: "Active",
    storeType: "Regular",
    city: "Bhopal",
    createdAt: new Date().toISOString()
  },
  {
    _id: "perf-3",
    storeId: "store-3",
    storeName: "Papa Veg Pizza - Ujjain Branch",
    date: "2026-06-20",
    totalOrders: 150,
    completedOrders: 145,
    cancelledOrders: 5,
    revenue: 30000,
    avgOrderValue: 200,
    avgPreparationTime: 15,
    avgDeliveryTime: 26,
    customerRating: 4.5,
    inventoryWaste: 3.1,
    performanceScore: 84,
    status: "Active",
    storeType: "Regular",
    city: "Ujjain",
    createdAt: new Date().toISOString()
  },
  {
    _id: "perf-4",
    storeId: "store-4",
    storeName: "Papa Veg Pizza - Gwalior Hub",
    date: "2026-06-20",
    totalOrders: 180,
    completedOrders: 176,
    cancelledOrders: 4,
    revenue: 32000,
    avgOrderValue: 178,
    avgPreparationTime: 13,
    avgDeliveryTime: 23,
    customerRating: 4.7,
    inventoryWaste: 2.0,
    performanceScore: 91,
    status: "Active",
    storeType: "Express",
    city: "Gwalior",
    createdAt: new Date().toISOString()
  },
  {
    _id: "perf-5",
    storeId: "store-5",
    storeName: "Papa Veg Pizza - Jabalpur Outlet",
    date: "2026-06-20",
    totalOrders: 120,
    completedOrders: 114,
    cancelledOrders: 6,
    revenue: 24000,
    avgOrderValue: 200,
    avgPreparationTime: 16,
    avgDeliveryTime: 28,
    customerRating: 4.4,
    inventoryWaste: 3.5,
    performanceScore: 78,
    status: "Active",
    storeType: "Regular",
    city: "Jabalpur",
    createdAt: new Date().toISOString()
  },
  {
    _id: "perf-6",
    storeId: "store-6",
    storeName: "Papa Veg Pizza - Dewas Kitchen",
    date: "2026-06-20",
    totalOrders: 90,
    completedOrders: 88,
    cancelledOrders: 2,
    revenue: 18000,
    avgOrderValue: 200,
    avgPreparationTime: 11,
    avgDeliveryTime: 21,
    customerRating: 4.3,
    inventoryWaste: 1.8,
    performanceScore: 86,
    status: "Active",
    storeType: "Cloud Kitchen",
    city: "Dewas",
    createdAt: new Date().toISOString()
  },
  {
    _id: "perf-7",
    storeId: "store-7",
    storeName: "Papa Veg Pizza - Pithampur Express",
    date: "2026-06-20",
    totalOrders: 80,
    completedOrders: 77,
    cancelledOrders: 3,
    revenue: 14400,
    avgOrderValue: 180,
    avgPreparationTime: 12,
    avgDeliveryTime: 22,
    customerRating: 4.2,
    inventoryWaste: 2.1,
    performanceScore: 82,
    status: "Active",
    storeType: "Express",
    city: "Pithampur",
    createdAt: new Date().toISOString()
  },
  {
    _id: "perf-8",
    storeId: "store-8",
    storeName: "Papa Veg Pizza - Ratlam Hub",
    date: "2026-06-20",
    totalOrders: 70,
    completedOrders: 68,
    cancelledOrders: 2,
    revenue: 13300,
    avgOrderValue: 190,
    avgPreparationTime: 10,
    avgDeliveryTime: 20,
    customerRating: 4.7,
    inventoryWaste: 1.5,
    performanceScore: 92,
    status: "Active",
    storeType: "Cloud Kitchen",
    city: "Ratlam",
    createdAt: new Date().toISOString()
  },
  {
    _id: "perf-9",
    storeId: "store-9",
    storeName: "Papa Veg Pizza - Sagar Outlet",
    date: "2026-06-20",
    totalOrders: 60,
    completedOrders: 58,
    cancelledOrders: 2,
    revenue: 11000,
    avgOrderValue: 183,
    avgPreparationTime: 15,
    avgDeliveryTime: 27,
    customerRating: 4.1,
    inventoryWaste: 3.8,
    performanceScore: 71,
    status: "Active",
    storeType: "Regular",
    city: "Sagar",
    createdAt: new Date().toISOString()
  },
  {
    _id: "perf-10",
    storeId: "store-10",
    storeName: "Papa Veg Pizza - Rewa Kitchen",
    date: "2026-06-20",
    totalOrders: 50,
    completedOrders: 49,
    cancelledOrders: 1,
    revenue: 9500,
    avgOrderValue: 190,
    avgPreparationTime: 11,
    avgDeliveryTime: 22,
    customerRating: 4.3,
    inventoryWaste: 2.0,
    performanceScore: 85,
    status: "Active",
    storeType: "Cloud Kitchen",
    city: "Rewa",
    createdAt: new Date().toISOString()
  },
  {
    _id: "perf-11",
    storeId: "store-11",
    storeName: "Papa Veg Pizza - Satna Branch",
    date: "2026-06-20",
    totalOrders: 65,
    completedOrders: 63,
    cancelledOrders: 2,
    revenue: 11700,
    avgOrderValue: 180,
    avgPreparationTime: 14,
    avgDeliveryTime: 25,
    customerRating: 4.2,
    inventoryWaste: 2.5,
    performanceScore: 79,
    status: "Closed",
    storeType: "Regular",
    city: "Satna",
    createdAt: new Date().toISOString()
  },
  {
    _id: "perf-12",
    storeId: "store-12",
    storeName: "Papa Veg Pizza - Katni Point",
    date: "2026-06-20",
    totalOrders: 45,
    completedOrders: 43,
    cancelledOrders: 2,
    revenue: 8100,
    avgOrderValue: 180,
    avgPreparationTime: 13,
    avgDeliveryTime: 23,
    customerRating: 4.0,
    inventoryWaste: 1.9,
    performanceScore: 75,
    status: "Closed",
    storeType: "Express",
    city: "Katni",
    createdAt: new Date().toISOString()
  },
  {
    _id: "perf-101",
    storeId: "store-101",
    storeName: "Papa Veg Pizza - Vijay Nagar",
    date: "2026-06-20",
    totalOrders: 140,
    completedOrders: 136,
    cancelledOrders: 4,
    revenue: 28000,
    avgOrderValue: 200,
    avgPreparationTime: 12,
    avgDeliveryTime: 22,
    customerRating: 4.6,
    inventoryWaste: 2.1,
    performanceScore: 90,
    status: "Closed",
    storeType: "Regular",
    city: "Indore",
    createdAt: new Date().toISOString()
  },
  {
    _id: "perf-102",
    storeId: "store-102",
    storeName: "Papa Veg Pizza - Palasia Cloud Kitchen",
    date: "2026-06-20",
    totalOrders: 95,
    completedOrders: 92,
    cancelledOrders: 3,
    revenue: 19000,
    avgOrderValue: 200,
    avgPreparationTime: 11,
    avgDeliveryTime: 21,
    customerRating: 4.4,
    inventoryWaste: 1.8,
    performanceScore: 87,
    status: "Closed",
    storeType: "Cloud Kitchen",
    city: "Indore",
    createdAt: new Date().toISOString()
  },
  {
    _id: "perf-103",
    storeId: "store-103",
    storeName: "Papa Veg Pizza - Ujjain Tower Chowk",
    date: "2026-06-20",
    totalOrders: 10,
    completedOrders: 10,
    cancelledOrders: 0,
    revenue: 2120,
    avgOrderValue: 212,
    avgPreparationTime: 12,
    avgDeliveryTime: 23,
    customerRating: 5.0,
    inventoryWaste: 1.0,
    performanceScore: 98,
    status: "Active",
    storeType: "Express",
    city: "Ujjain",
    createdAt: new Date().toISOString()
  },
  {
    _id: "perf-104",
    storeId: "store-104",
    storeName: "Papa Veg Pizza - Bhopal MP Nagar",
    date: "2026-06-20",
    totalOrders: 110,
    completedOrders: 105,
    cancelledOrders: 5,
    revenue: 22000,
    avgOrderValue: 200,
    avgPreparationTime: 15,
    avgDeliveryTime: 26,
    customerRating: 4.3,
    inventoryWaste: 3.0,
    performanceScore: 80,
    status: "Closed",
    storeType: "Regular",
    city: "Bhopal",
  }
];

export const initialOperatingHours = [
  {
    _id: "oh-1",
    storeId: "store-1",
    monday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    tuesday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    wednesday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    thursday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    friday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    saturday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    sunday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    holidaySchedule: [
      { date: "2026-08-15", reason: "Independence Day", isClosed: true },
      { date: "2026-10-22", reason: "Diwali Special Hours", isClosed: false, open: "11:00 AM", close: "05:00 PM" }
    ],
    auditLogs: [
      { updatedBy: "Super Admin", action: "Updated Monday Hours", date: "2026-06-20T10:00:00.000Z", remarks: "Extended closing to 11 PM" },
      { updatedBy: "System", action: "Created default hours", date: "2024-01-15T10:00:00.000Z", remarks: "Initial setup" }
    ],
    updatedBy: "Super Admin",
    updatedAt: "2026-06-20T10:00:00.000Z"
  },
  {
    _id: "oh-2",
    storeId: "store-2",
    monday: { open: "10:00 AM", close: "10:00 PM", isClosed: false },
    tuesday: { open: "10:00 AM", close: "10:00 PM", isClosed: false },
    wednesday: { open: "10:00 AM", close: "10:00 PM", isClosed: false },
    thursday: { open: "10:00 AM", close: "10:00 PM", isClosed: false },
    friday: { open: "10:00 AM", close: "11:00 PM", isClosed: false },
    saturday: { open: "10:00 AM", close: "11:00 PM", isClosed: false },
    sunday: { open: "10:00 AM", close: "10:00 PM", isClosed: false },
    holidaySchedule: [
      { date: "2026-08-15", reason: "Independence Day", isClosed: true }
    ],
    auditLogs: [
      { updatedBy: "System", action: "Created default hours", date: "2024-02-10T10:00:00.000Z", remarks: "Initial setup" }
    ],
    updatedBy: "Super Admin",
    updatedAt: "2026-06-19T09:30:00.000Z"
  },
  {
    _id: "oh-3",
    storeId: "store-3",
    monday: { open: "11:00 AM", close: "11:00 PM", isClosed: false },
    tuesday: { open: "11:00 AM", close: "11:00 PM", isClosed: false },
    wednesday: { open: "11:00 AM", close: "11:00 PM", isClosed: false },
    thursday: { open: "11:00 AM", close: "11:00 PM", isClosed: false },
    friday: { open: "11:00 AM", close: "11:00 PM", isClosed: false },
    saturday: { open: "11:00 AM", close: "11:00 PM", isClosed: false },
    sunday: { open: "11:00 AM", close: "11:00 PM", isClosed: true },
    holidaySchedule: [],
    auditLogs: [
      { updatedBy: "Manoj Joshi", action: "Closed Sundays", date: "2026-06-18T14:22:00.000Z", remarks: "Sunday staff weekly off scheduled" }
    ],
    updatedBy: "Manoj Joshi",
    updatedAt: "2026-06-18T14:22:00.000Z"
  },
  {
    _id: "oh-4",
    storeId: "store-4",
    monday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    tuesday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    wednesday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    thursday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    friday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    saturday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    sunday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    holidaySchedule: [
      { date: "2026-08-15", reason: "Independence Day", isClosed: true }
    ],
    auditLogs: [],
    updatedBy: "Super Admin",
    updatedAt: "2026-06-20T10:00:00.000Z"
  },
  {
    _id: "oh-5",
    storeId: "store-5",
    monday: { open: "10:00 AM", close: "10:00 PM", isClosed: false },
    tuesday: { open: "10:00 AM", close: "10:00 PM", isClosed: false },
    wednesday: { open: "10:00 AM", close: "10:00 PM", isClosed: false },
    thursday: { open: "10:00 AM", close: "10:00 PM", isClosed: false },
    friday: { open: "10:00 AM", close: "10:00 PM", isClosed: false },
    saturday: { open: "10:00 AM", close: "10:00 PM", isClosed: false },
    sunday: { open: "10:00 AM", close: "10:00 PM", isClosed: false },
    holidaySchedule: [],
    auditLogs: [],
    updatedBy: "Super Admin",
    updatedAt: "2026-06-15T08:15:00.000Z"
  },
  {
    _id: "oh-6",
    storeId: "store-6",
    monday: { open: "12:00 AM", close: "12:00 AM", isClosed: false },
    tuesday: { open: "12:00 AM", close: "12:00 AM", isClosed: false },
    wednesday: { open: "12:00 AM", close: "12:00 AM", isClosed: false },
    thursday: { open: "12:00 AM", close: "12:00 AM", isClosed: false },
    friday: { open: "12:00 AM", close: "12:00 AM", isClosed: false },
    saturday: { open: "12:00 AM", close: "12:00 AM", isClosed: false },
    sunday: { open: "12:00 AM", close: "12:00 AM", isClosed: false },
    holidaySchedule: [],
    auditLogs: [
      { updatedBy: "Super Admin", action: "Configured 24x7 Hours", date: "2026-06-20T10:00:00.000Z", remarks: "Cloud kitchen transition" }
    ],
    updatedBy: "Super Admin",
    updatedAt: "2026-06-20T10:00:00.000Z"
  },
  {
    _id: "oh-7",
    storeId: "store-7",
    monday: { open: "09:00 AM", close: "10:00 PM", isClosed: false },
    tuesday: { open: "09:00 AM", close: "10:00 PM", isClosed: false },
    wednesday: { open: "09:00 AM", close: "10:00 PM", isClosed: false },
    thursday: { open: "09:00 AM", close: "10:00 PM", isClosed: false },
    friday: { open: "09:00 AM", close: "10:00 PM", isClosed: false },
    saturday: { open: "09:00 AM", close: "10:00 PM", isClosed: false },
    sunday: { open: "09:00 AM", close: "10:00 PM", isClosed: false },
    holidaySchedule: [
      { date: "2026-08-15", reason: "Independence Day", isClosed: true }
    ],
    auditLogs: [],
    updatedBy: "Super Admin",
    updatedAt: "2026-06-20T10:00:00.000Z"
  },
  {
    _id: "oh-8",
    storeId: "store-8",
    monday: { open: "12:00 AM", close: "12:00 AM", isClosed: false },
    tuesday: { open: "12:00 AM", close: "12:00 AM", isClosed: false },
    wednesday: { open: "12:00 AM", close: "12:00 AM", isClosed: false },
    thursday: { open: "12:00 AM", close: "12:00 AM", isClosed: false },
    friday: { open: "12:00 AM", close: "12:00 AM", isClosed: false },
    saturday: { open: "12:00 AM", close: "12:00 AM", isClosed: false },
    sunday: { open: "12:00 AM", close: "12:00 AM", isClosed: false },
    holidaySchedule: [],
    auditLogs: [
      { updatedBy: "Super Admin", action: "Configured 24x7 Hours", date: "2026-06-20T10:00:00.000Z", remarks: "Cloud kitchen transition" }
    ],
    updatedBy: "Super Admin",
    updatedAt: "2026-06-20T10:00:00.000Z"
  },
  {
    _id: "oh-9",
    storeId: "store-9",
    monday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    tuesday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    wednesday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    thursday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    friday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    saturday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    sunday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    holidaySchedule: [
      { date: "2026-08-15", reason: "Independence Day", isClosed: true }
    ],
    auditLogs: [],
    updatedBy: "Super Admin",
    updatedAt: "2026-06-20T10:00:00.000Z"
  },
  {
    _id: "oh-10",
    storeId: "store-10",
    monday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    tuesday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    wednesday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    thursday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    friday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    saturday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    sunday: { open: "09:00 AM", close: "11:00 PM", isClosed: false },
    holidaySchedule: [
      { date: "2026-08-15", reason: "Independence Day", isClosed: true }
    ],
    auditLogs: [],
    updatedBy: "Super Admin",
    updatedAt: "2026-06-20T10:00:00.000Z"
  },
  {
    _id: "oh-11",
    storeId: "store-11",
    monday: { open: "09:00 AM", close: "10:00 PM", isClosed: true },
    tuesday: { open: "09:00 AM", close: "10:00 PM", isClosed: true },
    wednesday: { open: "09:00 AM", close: "10:00 PM", isClosed: true },
    thursday: { open: "09:00 AM", close: "10:00 PM", isClosed: true },
    friday: { open: "09:00 AM", close: "10:00 PM", isClosed: true },
    saturday: { open: "09:00 AM", close: "10:00 PM", isClosed: true },
    sunday: { open: "09:00 AM", close: "10:00 PM", isClosed: true },
    holidaySchedule: [],
    auditLogs: [],
    updatedBy: "Super Admin",
    updatedAt: "2026-06-20T10:00:00.000Z"
  },
  {
    _id: "oh-12",
    storeId: "store-12",
    monday: { open: "09:00 AM", close: "10:00 PM", isClosed: true },
    tuesday: { open: "09:00 AM", close: "10:00 PM", isClosed: true },
    wednesday: { open: "09:00 AM", close: "10:00 PM", isClosed: true },
    thursday: { open: "09:00 AM", close: "10:00 PM", isClosed: true },
    friday: { open: "09:00 AM", close: "10:00 PM", isClosed: true },
    saturday: { open: "09:00 AM", close: "10:00 PM", isClosed: true },
    sunday: { open: "09:00 AM", close: "10:00 PM", isClosed: true },
    holidaySchedule: [],
    auditLogs: [],
    updatedBy: "Super Admin",
    updatedAt: "2026-06-20T10:00:00.000Z"
  },
  {
    _id: "oh-101",
    storeId: "store-101",
    monday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    tuesday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    wednesday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    thursday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    friday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    saturday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    sunday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    holidaySchedule: [],
    auditLogs: [],
    updatedBy: "Super Admin",
    updatedAt: "2026-06-20T10:00:00.000Z"
  },
  {
    _id: "oh-102",
    storeId: "store-102",
    monday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    tuesday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    wednesday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    thursday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    friday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    saturday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    sunday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    holidaySchedule: [],
    auditLogs: [],
    updatedBy: "Super Admin",
    updatedAt: "2026-06-20T10:00:00.000Z"
  },
  {
    _id: "oh-103",
    storeId: "store-103",
    monday: { open: "09:00 AM", close: "10:00 PM", isClosed: false },
    tuesday: { open: "09:00 AM", close: "10:00 PM", isClosed: false },
    wednesday: { open: "09:00 AM", close: "10:00 PM", isClosed: false },
    thursday: { open: "09:00 AM", close: "10:00 PM", isClosed: false },
    friday: { open: "09:00 AM", close: "10:00 PM", isClosed: false },
    saturday: { open: "09:00 AM", close: "10:00 PM", isClosed: false },
    sunday: { open: "09:00 AM", close: "10:00 PM", isClosed: false },
    holidaySchedule: [],
    auditLogs: [],
    updatedBy: "Super Admin",
    updatedAt: "2026-06-20T10:00:00.000Z"
  },
  {
    _id: "oh-104",
    storeId: "store-104",
    monday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    tuesday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    wednesday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    thursday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    friday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    saturday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    sunday: { open: "09:00 AM", close: "11:00 PM", isClosed: true },
    holidaySchedule: [],
    auditLogs: [],
    updatedBy: "Super Admin",
    updatedAt: "2026-06-20T10:00:00.000Z"
  }
];
